name: Build Gradle project

on:
  push:
    branches:
      - main

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Apply Executable Bit To Script For Release Notes
        run: chmod a+x release-notes.sh

      - name: Create Release Notes
        run: ./release-notes.sh

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          name: Release v ${{ env.GITHUB_APP_VERSION_NAME }}
          token: ${{ secrets.TOKEN }}
          tag: ${{ github.run_number }}
          artifacts: "app/build/outputs/apk/release/app-release.apk,release-notes.txt"

      - name: Increase Version Number
        uses: ults-io/mobile-version-bump-action@v1
        with:
            android-project-path: ./
            bump-type: patch

      - name: Update wiki pages
        uses: OrlovM/Wiki-Action@v1
        with:
            path: 'wiki'
            token: ${{ secrets.TOKEN }}