name: Build Gradle project

on:
  push:
    branches:
      - main

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      deployments: write
      pages: write

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Prepare Version Number
        run: |
          export GRADLE_PATH=./version.properties;
          export GRADLE_FIELD_VC="versionCode"
          export GRADLE_FIELD_VN="versionName"
          export VERSION_VC_TMP=$(grep $GRADLE_FIELD_VC $GRADLE_PATH | cat $2)
          export VERSION_VN_TMP=$(grep $GRADLE_FIELD_VN $GRADLE_PATH | cat $2)
          export VERSION_CODE=$(echo $VERSION_VC_TMP | sed -e 's/^versionCode=//'  -e 's/"$//')
          export VERSION_NAME=$(echo $VERSION_VN_TMP | sed -e 's/^versionName=//'  -e 's/"$//')
          echo "Release Version : (VC : $VERSION_CODE, VN: $VERSION_NAME)"
          echo "GITHUB_APP_VERSION_CODE=$(echo $VERSION_CODE)" >> $GITHUB_ENV
          echo "GITHUB_APP_VERSION_NAME=$(echo $VERSION_NAME)" >> $GITHUB_ENV

      - name: Create Release Notes
        run: |
          chmod a+x ./release-notes.sh
          ./release-notes.sh

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          name: Release v ${{ env.GITHUB_APP_VERSION_NAME }}
          token: ${{ secrets.TOKEN }}
          tag: ${{ github.run_number }}
          artifacts: "./app/build/outputs/apk/release/app-release.apk, ./release-notes.txt"

      - name: Increase Version Number
        uses: chkfung/android-version-actions@v1.2.1
        with:
          gradlePath: app/build.gradle
          versionCode: ${{ env.GITHUB_APP_VERSION_CODE }}
          versionName: ${{ env.GITHUB_APP_VERSION_NAME }}

      - name: Commit Files
        run: |
          rm -rf ./version.properties
          rm -rf ./release-notes.txt
          git config --global user.name 'Milan Jurkulak'
          git config --global user.email 'mimoccc@gmail.com'
          git add .
          git commit -a -m "Add changes"

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: ${{ github.ref }}

      - name: Merge Changes
        uses: fastify/github-action-merge-dependabot@v2.1.1
        with:
          github-token: ${{ secrets.TOKEN }}

      - name: Update wiki pages
        uses: OrlovM/Wiki-Action@v1
        with:
          path: 'wiki'
          token: ${{ secrets.TOKEN }}