name: Build Gradle project

on:
  push:
    branches:
      - main

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      deployments: write
      pages: write

    steps:
      - name: Checkout project sources
        id: checkout_project
        uses: actions/checkout@v3

      - name: Set up JDK 17
        id: setup_java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        id: setup_gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        id: grant_gradle
        run: chmod +x gradlew

      - name: Build Release APK
        id: build_release_apk
        run: ./gradlew assembleRelease

      - name: Prepare Version Number
        id: prepare_version
        run: |
          export GRADLE_PATH=./version.properties;
          export GRADLE_FIELD_VC="versionCode"
          export GRADLE_FIELD_VN="versionName"
          export VERSION_VC_TMP=$(grep $GRADLE_FIELD_VC $GRADLE_PATH | cat $2)
          export VERSION_VN_TMP=$(grep $GRADLE_FIELD_VN $GRADLE_PATH | cat $2)
          export VERSION_CODE=$(echo $VERSION_VC_TMP | sed -e 's/^versionCode=//'  -e 's/"$//')
          export VERSION_NAME=$(echo $VERSION_VN_TMP | sed -e 's/^versionName=//'  -e 's/"$//')
          echo "Release Version : (VC : $VERSION_CODE, VN: $VERSION_NAME)"
          echo "GITHUB_APP_VERSION_CODE=$(echo $VERSION_CODE)" >> $GITHUB_ENV
          echo "GITHUB_APP_VERSION_NAME=$(echo $VERSION_NAME)" >> $GITHUB_ENV

      - name: Create Release Notes
        id: create_release_notes
        run: |
          chmod a+x ./release-notes.sh ${{ env.GITHUB_APP_VERSION_NAME }} dev
          ./release-notes.sh

      - name: Create Release
        id: release
        uses: ncipollo/release-action@v1
        with:
          name: Release v ${{ env.GITHUB_APP_VERSION_NAME }}
          token: ${{ secrets.TOKEN }}
          tag: ${{ github.run_number }}
          artifacts: './app/build/outputs/apk/release/app-release.apk, ./release-notes.txt'

      - name: Bump version
        id: bump_version
        uses: oflynned/android-version-bump@master
        with:
          commit_message: 'bump version'
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Update wiki pages
        id: update_wiki_pages
        uses: OrlovM/Wiki-Action@v1
        with:
          path: 'wiki'
          token: ${{ secrets.TOKEN }}