name: Build Gradle project

on:
  push:
    branches:
      - main

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
            java-version: '17'
            distribution: 'temurin'
            cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Check files
        run: ls -al app/build/outputs/apk/release

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          name: Release ${{ github.event.repository.name }} v${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
          tag: ${{ github.run_number }}
          artifacts: "app/build/outputs/apk/release/app-release.apk"